version: '3.9'

services:
  remote:
    image: lekliu/liuproxy-remote:v2.0
    build:
      context: .
      dockerfile: Dockerfile
      target: remote
    ports:
      - "127.0.0.1:10089:10089"

  local:
    image: lekliu/liuproxy-local:v2.0
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    volumes:
      # 格式: <本地路径>:<容器内路径>
      - ./configs/local.ini:/app/configs/local.ini
    ports:
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:9088:9088"